name: Node CI

on: [pull_request]

jobs:
  build:
    timeout-minutes: 20

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.1

      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: LocalStack Docker Image Cache
        uses: actions/cache@v3
        id: cache-docker-localstack
        with:
          path: var/lib/docker
          key: localstack-docker-image-${{ runner.os }}

#      - name: Store LocalStack Docker Image Cache
#        if: steps.cache-docker-localstack.outputs.cache-hit != 'true'
#        run: docker pull localstack/localstack && mkdir -p ci/cache/docker/localstack && docker image save localstack/localstack --output ./ci/cache/docker/localstack/localstack.tar
#
#      - name: Load LocalStack Docker Image Cache
#        if: steps.cache-docker-localstack.outputs.cache-hit == 'true'
#        run: docker image load --input ./ci/cache/docker/localstack/localstack.tar

      - name: Test
        run: pnpm test
